__title__ = "pipenv-devcheck"
__description__ = "Pipenv/setup.py dependency comparison tool"
__url__ = "https://github.com/neighborhoods/pipenv-devcheck"
__version__ = "0.4.0"
__author__ = "George Wood (@Geoiv)"
__author_email__ = "george.wood@55places.com"
__license__ = "MIT"
